# Generated by Django 4.1.3 on 2022-11-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_watch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.TextField(default='1/1/2022'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(),
        ),
    ]
